version: 2.1

jobs:
  build-and-test:
    working_directory: ~/repo

    docker:
      - image: circleci/node:14.16

    steps:
      - checkout

      # Restore dependencies from cache if available
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      # Save dependencies to cache for future builds
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Build Android APK
          command: yarn android:build
        when: on_success

      - run:
          name: Run Android Tests
          command: yarn android:test
        when: on_success

      - run:
          name: Build iOS App
          command: yarn ios:build
        when: on_success

      - run:
          name: Run iOS Tests
          command: yarn ios:test
        when: on_success

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
