version: 2.1

orbs:
  gh: circleci/github-cli@2.1.1
  slack: circleci/slack@4.10.1
  node: circleci/node@5.0.3
  ruby: circleci/ruby@2.0.0

jobs:
  node:
    working_directory: ~/ReactNaviteProject
    docker:
      - image: cimg/node:16.10

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/ReactNaviteProject
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  ios_alpha:
    working_directory: ~/ReactNaviteProject
    macos:
      xcode: "14.2.0"
    resource_class: macos.x86.medium.gen2

    environment:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      HOMEBREW_NO_AUTO_UPDATE: 1
    
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      #Pods directory is ignored to match default RN setup, but can also check them into source control
      #https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
      - restore_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}

      - run: 
          command: pod install
          working_directory: ios

      - save_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
          paths:
            - ios/Pods

      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      - run: 
          command: bundle install
          working_directory: ios

      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run: echo 'chruby ruby-2.6' >> ~/.bash_profile
      - run: bundle install
      - run: curl -sL https://firebase.tools | bash

      - run:
          name: Build and deploy the iOS app to Firebase
          command: bundle exec fastlane deploy_ios_alpha_app_fire_base
          working_directory: ios

      # - run:
      #     name: Build the iOS app
      #     command: bundle exec fastlane deploy_ios_alpha_app
      #     working_directory: ios    

      - store_artifacts:
          path: ./build/ReactNativeProject.ipa
          
      - store_test_results:
          path: ./build/scan

  ios_beta:
    working_directory: ~/ReactNaviteProject
    macos:
      xcode: "14.2.0"
    resource_class: macos.x86.medium.gen2

    environment:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      HOMEBREW_NO_AUTO_UPDATE: 1
    
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      #Pods directory is ignored to match default RN setup, but can also check them into source control
      #https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
      - restore_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}

      - run: 
          command: pod install
          working_directory: ios

      - save_cache:
          key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
          paths:
            - ios/Pods

      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      - run: 
          command: bundle install
          working_directory: ios

      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: Build the iOS app
          command: bundle exec fastlane deploy_ios_beta_app
          working_directory: ios    

      - store_artifacts:
          path: ./build/ReactNativeProject.ipa
          
      - store_test_results:
          path: ./build/scan
            
  android-build-and-test:
    working_directory: ~/ReactNaviteProject/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/ReactNaviteProject

      - attach_workspace:
          at: ~/ReactNaviteProject

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane tests
          command: |
            mkdir -p test-results/fastlane
            bundle exec fastlane test
            mv fastlane/report.xml test-results/fastlane

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

workflows:
  version: 2
  feature_test:
    jobs:
      - node
      - ios_alpha:
          requires:
            - node
          filters:
            branches:
              ignore:
                - develop
                - /rc-.*/
                - production
                - /v[0-9]*.[0-9]*/
      # - ios_beta:
      #     requires:
      #       - node
      #     fileters:
      #       branches:
      #         only:
      #           - /rc-.*/
      #           - /fix-.*/
            