# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    # macos:
      # xcode: 14.2.0
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    # docker:
    #  - image: circleci/node@5.0.2
    executor: node/default
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install Dependencies
          command: yarn install

     # - run:
     #     name: Build Android APK
     #     command: yarn build:android

      - run: 
          command: bundle exec pod install
          working_directory: ios

      - run:
          name: Build iOS App
          command: yarn build:ios     

# Orchestrate jobs using workflows.
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
